---
description: Pipeline for parsing salesforce login logs
processors:
- set:
    field: event.ingested
    value: '{{_ingest.timestamp}}'
- remove:
    field:
      - message
    ignore_missing: true

- set:
    field: salesforce.access_mode
    value: stream
    ignore_failure: true

- date:
    field: json.EventDate
    target_field: "@timestamp"
    formats: ["yyyy-MM-ddTHH:mm:ssZ"]
    ignore_failure: true

- rename: 
    field: json.schema
    target_field: salesforce.logout.schema
    ignore_missing: true
- rename: 
    field: json.CreatedById
    target_field: salesforce.logout.created_by_id
    ignore_missing: true
- rename: 
    field: json.RelatedEventIdentifier
    target_field: salesforce.logout.related_event_identifier
    ignore_missing: true
- rename: 
    field: json.LoginKey
    target_field: salesforce.logout.login_key
    ignore_missing: true
- rename: 
    field: json.SessionLevel
    target_field: salesforce.logout.session_level
    ignore_missing: true
- rename: 
    field: json.replayId
    target_field: salesforce.logout.replay_id
    ignore_missing: true

#######################
## ECS Event Mapping ##
#######################

- date:
    field: json.CreatedDate
    target_field: event.created
    formats: ["yyyy-MM-ddTHH:mm:ssZ"]
    ignore_failure: true
- set:
    field: event.type
    value: "info"
- set:
    field: event.kind
    value: "event"
- set:
    field: event.action
    value: "logout"
- set:
    field: event.category
    value: "authentication"
- set:
    field: event.dataset
    value: "salesforce.logout"
- set:
    field: event.module
    value: "salesforce"

######################
## ECS User Mapping ##
######################

- rename: 
    field: json.Username
    target_field: user.email
    ignore_missing: true
- rename: 
    field: json.UserId
    target_field: user.id
    ignore_missing: true

########################
## ECS Source Mapping ##
########################

- rename:
    field: json.SourceIp
    target_field: source.ip
    ignore_missing: true

############################
## ECS Source.Geo Mapping ##
############################

- geoip:
    field: source.ip
    target_field: source.geo
    ignore_missing: true

#############
## Cleanup ##
#############

- remove:
    field:
      - json
    ignore_missing: true
on_failure:
- set:
    field: error.message
    value: '{{_ingest.on_failure_message}}'
